name: pypi-deploy

on:
  release:
    types: [published]

jobs:
  deploy:
    name: Build and deploy the package to PyPI
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: "3.9"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade build
        pip install --upgrade twine
    - name: Build package
      run: |
        python -m build --outdir dist/
        twine check dist/*
    - name: Publish package
      uses: pypa/gh-action-pypi-publish@master
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
        verbose: true
